### ISSUE TITLE
[SUGESTÃO] adicionar link em ABOUT e atualizar README

### ISSUE THREAD

**Issue by Cauatn** [SOS-RS/frontend#104]
Sugiro adicionar o About da mesma forma que foi feita a iniciativa backend.
Atualizar o README desse projeto para a mesma estrutura que foi utilizado ao back também seria interessante , complementado a sugestão que a Carol fez em https://github.com/SOS-RS/frontend/issues/31#issue-2288464694.
Parabéns pela iniciativa.

![image](https://github.com/SOS-RS/frontend/assets/39890456/8067c65d-5e28-4ba5-aa61-f11e764570fb)

**Comment by salescamila** [comment]
About do projeto atualizado com o link do site
