### ISSUE TITLE
Onde está o backlog do projeto?

### ISSUE THREAD

**Issue by Pekito** [SOS-RS/frontend#108]
Gostaria de saber como está o mapeamento das atividades em andamento e tarefas disponíveis para serem escolhidas por desenvolvedores voluntários.

**Comment by LucasJantschChitolina** [comment]
@Pekito, a maioria das discussões estão acontecendo no Discord https://discord.com/channels/1237553809371299950/1238173828262400070

Lá você pode ver os #links-uteis e as #faq do projeto

**Comment by logycware** [comment]
Não consegui acesso ao canal no discord pelo link indicado, gostaria de ajudar

**Comment by Pekito** [comment]
@logycware @alexanderscheibler achei o discord lá numa postagem do linkedin, segue -> https://discord.com/invite/92d6nQRF

**Comment by marvindev2022** [comment]
Tenho acesso as task no discord? ou vejo as demandas em issues?

**Comment by viniirbr** [comment]
Aqui o backlog: https://trello.com/b/YlbqtbDM/backlog-sos-rs

**Comment by felipecastilhos** [comment]
@viniirbr ao acessar o link aparece como quadro não encontrado

**Comment by paulo-fs** [comment]
Mesma coisa, quadro não encontrado =/

**Comment by maraMoreir** [comment]
Quadro e link do discord não foi encontrado aqui, alguém por favor consegue mandar o link atualizado pra podermos colaborar ?

**Comment by viniirbr** [comment]
Foi mal, galera. Pelo que falaram no Discord, parece que a organização pelo Trello não funcionou direito e o pessoal está trabalhando em uma nova forma de organizar as demandas. Por enquanto, consultem os issues

**Comment by giggio** [comment]
Pessoal, criamos aqui no Github projects: https://github.com/orgs/SOS-RS/projects/1
