### ISSUE TITLE
[Sugestão] - Adicionar uma área para upload de imagens de crianças/adultos separados de seus parentes. 

### ISSUE THREAD

**Issue by La-Rocca** [SOS-RS/frontend#117]

**Comment by La-Rocca** [comment]
Para fins de provacidade, podemos colocar tarjas pretas em volta dos olhos.

**Comment by MatheusDubin** [comment]
Olá @La-Rocca,

Foi considerado a introdução de um módulo com essa finalidade. No entanto, devido à sensibilidade de lidar com esse tipo de dado em relação à Lei Geral de Proteção de Dados, à confiabilidade da informação e à própria segurança das pessoas que seriam registradas, entendemos que não faz sentido abraçarmos essa demanda no software.

Sei que neste momento não é o que se quer ouvir, mas há diversas soluções diferentes que já tem esse foco e estão funcionando.

Muito obrigado

**Comment by La-Rocca** [comment]
Entendo perfeitamente. Bom saber que outras opções estão sendo consideradas. Parabéns pelo excelente trabalho, tenho tentado divulgar como posso esse projeto.
