### ISSUE TITLE
[Sugestão] Criar página de Visão Geral (Dashboard)

### ISSUE THREAD

**Issue by dududecastro** [SOS-RS/frontend#121]
FIGMA: https://www.figma.com/file/CKPIWWqE4YEPXbtEmB2UNL/SOS-RS?type=design&node-id=1%3A2&mode=design&t=ekD7Wpa3k2izJl12-1

Criar uma página para totalizar as informações de abrigos, necessidades por categoria e disponibilidade.
A ideia é ter links nos itens para direcionar para a listagem geral filtrada.

Dentro dos cards de necessidade, os indicadores são o número total de abrigos que tem necessidades daquela categoria marcadas como: urgente, precisa e disponível para doação. É interessante ter um tooltip (que seja exibido também ao clicar, para mobile)

**Comment by mateusfnogueira** [comment]
Alguém já pegou esse card? se não vou pega-lo

**Comment by mateusfnogueira** [comment]
Estou fazendo essa issue

**Comment by rafael-alves-cs** [comment]
Sugiro dar uma olhada nessa iniciativa aqui: https://www.linkedin.com/posts/bruno-paiva-bp_dashboard-sos-rs-activity-7195798407725170688-g74p?utm_source=share&utm_medium=member_desktop

**Comment by rhuam** [comment]
@mateusfnogueira necessário resolver os conflitos.

**Comment by mateusfnogueira** [comment]
> @mateusfnogueira necessário resolver os conflitos.

O pr está em draft, quando eu mudar para open eu resolveria os conflitos, ainda preciso que o back esteja em prod para estar pronto para mergear
