### ISSUE TITLE
Link para Cadastro de Novos Abrigos escondido

### ISSUE THREAD

**Issue by jaquelinebonoto** [SOS-RS/frontend#13]
Olá!

Sugiro fixar o footer da página pois o link de cadastro de novos abrigos e até mesmo o link de repositório do github ficam escondidos, a menos que voce faça uma busca bem restritiva.

**Comment by herr-berna** [comment]
Poderia ter mais um link na página, mais visível, para cadastro de abrigo.

**Comment by smolskig** [comment]
Vou sugerir pra criarmos um botão na barra superior, mais chamativo e intuitivo.
Faz mais sentido do que ter ele no footer da página.

**Comment by hick-ferreira** [comment]
Olá. Adicionei esse botão no Header e fiz um pull request.
