### ISSUE TITLE
[BUG] Ordenação alfabética invertida nos filtros

### ISSUE THREAD

**Issue by Ardnna** [SOS-RS/frontend#144]
Descrição issue:

Ao acessar sos-rs.com , e realizar a busca por filtros, o menu ítens aparece em Ordenação alfabética invertida, onde o final do alfabeto aparece antes do inicio. O menu Categoria não está ordenado alfabeticamente

Resultado esperado:

Números em ordem crescenteaparecem primeiro, posteriormente alfabeto em sequencia inicial começando pela letra A (ordem alfabética). Este comportamento deve se aplicar a todos os dropdowns para seleção em Filtros (Itens, Categorias).

Teste:

- Acesse o site sos-rs.com
- Selecione a opção "Filtros"
- Expanda cada uma das opções de menu dropdown no modal exibido
- Confira se as informações estão em órdem alfabética, exibindo Primeiramente números em ordem crescente e posteriormente Letras.

![Captura de tela 2024-05-14 100729](https://github.com/SOS-RS/frontend/assets/77037409/82e322b2-afda-4d2b-b1ea-1ff2e4757180)

![Captura de tela 2024-05-14 100954](https://github.com/SOS-RS/frontend/assets/77037409/a7c70d3b-3236-4e71-8a1f-b71018351c65)

**Comment by HbLuca** [comment]
Realizado o teste e o comportamento está de acordo, conforme Loom:

https://www.loom.com/share/433586d8fd8e49feadc3835712e65fea?sid=b4c6186e-4a5c-4a76-87ea-3c4e2e9bcb76

**Comment by HbLuca** [comment]
Realizado e testado, de acordo.
