### ISSUE TITLE
[BUG] Ordenação alfabética invertida ao editar itens do abrigo

### ISSUE THREAD

**Issue by alexanderscheibler** [SOS-RS/frontend#163]
# Descrição

Ao entrar para editar os itens de um abrigo, os itens de cada categoria estão com a ordenação invertida de Z para A. 

# Problema encontrado

Torna mais difícil encontrar os itens do que seguindo a ordenação A-Z, geralmente padrão.

# Prioridade
Baixa

# Solução proposta

Inverter a ordenação dos itens em cada categoria para que seja alfabética.

# Pontos a salientar

Talvez isso impacte um pouco usuários que já estão acostumados a cadastrar muitos itens, entretanto acredito que possa trazer um benefício para novos usuários a medida que o sistema é escalado.

# Ambiente
Samsung S23FE, Google Chrome

# Evidência

![ordenacao](https://github.com/SOS-RS/frontend/assets/60936422/e766c14e-9e75-4155-be2b-e93cc4b96678)

**Comment by gi-carnaval** [comment]
Correção no PR #166 
[fix: ordering the list of items on the shelter edit page #166](https://github.com/SOS-RS/frontend/pull/166)

**Comment by HbLuca** [comment]
Se este for corrigido, deve encerrar o [144] (https://github.com/SOS-RS/frontend/issues/144)

**Comment by Fernandasouzaf** [comment]
Verifiquei que no filtro da página principal de abrigos, também esta ordenado de Z-A
![image](https://github.com/SOS-RS/frontend/assets/103526949/3af0d835-3552-4c48-b2da-244f3da5e08c)

**Comment by HbLuca** [comment]
@Fernandasouzaf no https://github.com/SOS-RS/frontend/issues/144 a @Ardnna, menciona sobre.

**Comment by Fernandasouzaf** [comment]
> @Fernandasouzaf no #144 a @Ardnna, menciona sobre.

Entendi, obrigada por avisar.

**Comment by andradeviniicius** [comment]
Acredito que da pra fechar essa issue @HbLuca a solução já está em prod

**Comment by HbLuca** [comment]
@andradeviniicius se fosse eu o criador, poderia até fechar. Teria de ver com o @alexanderscheibler, sobre.

E referente ao https://github.com/SOS-RS/frontend/issues/144, já sinalizei a @Ardnna 

Acabei de realizar o teste e está de acordo, conforme loom:
https://www.loom.com/share/433586d8fd8e49feadc3835712e65fea?sid=b4c6186e-4a5c-4a76-87ea-3c4e2e9bcb76

Mas me ficou uma questão...
Adicionaram no pop-up a parte de cidades, não poderia contemplar também a parte de ordenação?
![image](https://github.com/SOS-RS/frontend/assets/108205892/967772ee-357a-4e09-af4a-5921e368409f)
@gi-carnaval que fez o https://github.com/SOS-RS/frontend/pull/166

**Comment by gi-carnaval** [comment]
A ordenação das cidades está sendo feita por quantidade de abrigos registrados na cidade. Não sei se ordenar alfabeticamente seria a melhor apresentação. Mas caso necessário, posso implementar sim!!

**Comment by HbLuca** [comment]
@alexanderscheibler @ardnna que abriram tanto este, quanto o (https://github.com/SOS-RS/frontend/issues/144), o que acham?

Ordenação de cidade por ordem alfabética, seguindo o restante (categoria e itens) ou por quantidade de abrigos registrados na cidade?

**Comment by Ardnna** [comment]
Acredito particularmente por ordem alfabética mesmo é o ideal! A não ser
que existisse um aviso muito especifico determinamdo qual a ordem, é mais
intuitivo localizar por ordem alfabética!

Em qui., 16 de mai. de 2024 12:01, HbLuca ***@***.***>
escreveu:

**Comment by gi-carnaval** [comment]
Estou trabalhando nisso!! Logo entrego a implementação!!

**Comment by alexanderscheibler** [comment]
> Ordenação de cidade por ordem alfabética, seguindo o restante (categoria e itens) ou por quantidade de abrigos registrados na cidade?

Sugiro o padrão que vi em muitos lugares:
- Capital primeiro
- Seguem todas as outras cidades por ordem alfabética

Isso se justifica pois acredito que a capital deva ter bem mais abrigos que todas as outras cidades (evita bastante gente ter que rolar até bem embaixo pra achar), mas mantém a ordenação alfabética para as outras cidades serem achadas facilmente.

Como esse bug foi resolvido, estou encerrando o tópico.

**Comment by Ardnna** [comment]
Tua sugestão faz bastante sentido!

O principal do bug foi fechado já que estava em ordem de inserção, mas acho
que é uma boa! Inclusive para melhorias futuras do filtro, escolher uma
forma de ordenação por exemplo (mais vagas primeiro) ou algo assim!

Em sex., 17 de mai. de 2024 00:20, Alexander Scheibler <
***@***.***> escreveu:
