### ISSUE TITLE
[BUG] Itens extras ou ausentes da categoria "Medicamentos"

### ISSUE THREAD

**Issue by alexanderscheibler** [SOS-RS/frontend#164]
# Descrição
Ao acessar a tela para adicionar item a um abrigo, existem muitos itens que não pertencem a categoria "Medicamentos", mas aparecem como se incluídos nela ao tentar adicionar items a um abrigo - e outros que poderiam estar nessa categoria estão em outras categorias.

# Problema encontrado
Categoria Medicamentos poluída com itens que não pertencem a ela - e tendo ausência de itens que poderiam estar lá.

Os seguintes itens poderiam estar incluídos na categoria Medicamentos (atualmente, estão nas categorias citadas):
Incluído em "Higiene":
- Xarope Para Gripe

Incluído em "Outros":
- Descarpack
- Tipoia Velpeau
- Caneta Insulina Tresiba (degludeca)
- Caneta Insulina Lispro Humalog (

Os seguintes itens provavelmente não deveriam estar incluídos na categoria Medicamentos:
- Voluntários Para Recreação
- Ventilador
- Tomate
- Toddy
- Tênis 36-39
- Talheres Descartáveis
- Sucos
- Saquinhos de Sacolé
- Saladas
- Sal
- Sacos de lixo
- Sacolas Plásticas Médias
- Sabão Em Pó
- Roupas Plus Size Frio
- Roupas Masculinas De Moletom G A Xxg (casacos e Calças)
- Roupas Masculinas
- Roupas Maculinas
- Roupas Intimas
- Roupas de 10 - 14 Anos
- Roupa Infantil Menino
- Repelente
- Ração Senior
- Produtos de Limpeza
- Produtos de Higiene
- Prendedores
- Prednizolona Para Animais
- Potes De Plástico
- Polenta
- Pipeto Para Caes Grandes
- Peiteira/Coleira Grande
- Pasta de Dente
- Óleo de Cozinha
- Óleo
- Não Precisa de Voluntários

Entre muitos outros...

# Prioridade
Baixa

# Solução proposta

Ajustar o cadastro dos itens mencionados vinculando-os à categoria correta

# Ambiente
Samsung S23FE, Google Chrome

# Evidência
![image](https://github.com/SOS-RS/frontend/assets/60936422/d14af1d4-dc67-4320-af5f-dad1945bd936)
![image](https://github.com/SOS-RS/frontend/assets/60936422/8e212735-8221-44d0-a91d-11c62152fe1c)

**Comment by alexanderscheibler** [comment]
Relacionado: https://github.com/SOS-RS/frontend/issues/287

**Comment by rhuam** [comment]
Também resolvido pelo #287
