### ISSUE TITLE
[SUGESTÃO] adicionar o feedback para quantos pets estão abrigados

### ISSUE THREAD

**Issue by djedu28** [SOS-RS/frontend#173]
# [SUGESTÃO] adicionar o feedback para quantos pets estão abrigados

Pelo que percebi pelo front-end o abrigo para pets está cadastrado jundo com abrigos para pessoas, sem categorizar os mesmos, a única diferença tá no nome (titulo) do abrigo

Ótimo dar o feedback de quantas pessoas estão abrigadas no local, pode ser um ponto importante na decisão de onde direcionar recursos.
![image](https://github.com/SOS-RS/frontend/assets/43933482/58df4570-e942-4de5-9cae-c8dc8030c118)

Da mesma forma, ter a quantidade de pets que estão sendo abrigados ajuda na decisão de quem tem os recursos e quer levar aos animais que também precisam de cuidados.

## Prioridade

BAIXA

## dicas para a solução

* Adicionar uma nova linha no frontend com a quantidade de pets abrigados
* Adicionar no banco de dados a coluna da quantidade de pets abrigados e propagar as mudanças no backend
* Adicionar no banco de dados a categoria de abrigo (só para humanos, só para pets, ou humanos e pets domésticos)
* Adicionar no banco de dados e front a capacidade do abrigo para pets domésticos

## vale até um ponto, quando falei de categorias de abrigo

citei as categorias - só para humanos, só para pets domésticos, ou humanos + pets domésticos
é relevante adicionar tambem a categoria centro de distribuição, um local onde a população necessitade pode ir buscar suprimentos, mas não tem espaço para servir de abrigo

**Comment by giggio** [comment]
Duplicado do #259.
