### ISSUE TITLE
Adicionar filtro para facilitar a busca

### ISSUE THREAD

**Issue by ecsistem** [SOS-RS/frontend#19]
Adicionar filtro para buscar abrigos que não estejam lotado

**Comment by gustavoluchi** [comment]
1) Essa info existe no backend?
2) Essa info já é mandada pro frontend? (se a consulta não for paginada dá pra filtrar no front daí)
3) se a consulta é paginada, a consulta está pronta pra receber o filtro 'não lotado'? Se não estiver, é preciso criar uma issue no backend e esperar ficar pronto lá primeiro.
