### ISSUE TITLE
[BUG] Ficar aparecendo para qualquer um editar

### ISSUE THREAD

**Issue by nadodev** [SOS-RS/frontend#203]
# Descrição
Navegando no site, notei que fica aparecendo a opção de editar um abrigo, acho que isso não é correto.

# Problema encontrado
Aparecendo opção de editar abrigo para qualquer pessoa

# Prioridade
- Grave

# Solução proposta
Fazer alguma forma de autenticação para administradores ou para o próprio abrigo poder editar.

# Evidência

![image](https://github.com/SOS-RS/frontend/assets/68485328/8622c0c0-46cd-45a9-80de-e9e3416b63f3)

**Comment by Michelsgab** [comment]
Mas essa edição deveria ser permitida só para quem? Quem foi que fez a publicação?

**Comment by nadodev** [comment]
Pelo menos na minha visão sim, porque se não pode haver até pessoas mal intencionadas e editar.  até porque quem vai saber sobre as organização é a própria organização.

**Comment by HbLuca** [comment]
https://discord.com/channels/1237553809371299950/1240079546934624276
Neste tópico do Discord, é abordado tal assunto.

@nadodev @Michelsgab

**Comment by nadodev** [comment]
Se acha que todo os abrigados vão ter acesso a um celular ou um computador?

**Comment by HbLuca** [comment]
Por enquanto, seguirá como proposto em conversa, que a feature seguirá assim.
