### ISSUE TITLE
[SUGESTÃO DE MELHORIA] Adicionar um tooltip no botão de refresh

### ISSUE THREAD

**Issue by devgl96** [SOS-RS/frontend#210]
# Descrição
Relacionado com o botão de atualização dos abrigos.

# Problema encontrado
Percebi que o botão de atualizar as informações, não tinha qualquer informação.

# Prioridade
Baixa

# Solução proposta
Criei um tooltip usando apenas o TailwindCSS. 
Link da PR: https://github.com/SOS-RS/frontend/pull/209

# Ambiente
Navegador Brave 

# Evidência
Solução:
![image](https://github.com/SOS-RS/frontend/assets/44107959/aec8269c-a90f-40d2-86d9-a3723fa94015)

**Comment by MarioPonte** [comment]
Acho que seria uma boa adição, quando entrei pela primeira vez tambem fiquei na dúvida do que esse botão poderia representar. Foi bastante fácil perceber que era para atualizar as informações mas para quem não está dentro da área pode não perceber. O **shadcn-ui** (que já está integrado no projeto) contem um **componente Tooltip** já pronto que é bastante eficaz, caso aprovem a sugestão recomendava que esse componente fosse usado.

**Comment by devgl96** [comment]
Implementei uma solução usando apenas o TailwindCSS para evitar imports de bibliotecas. 
Você pode ver nessa PR: https://github.com/SOS-RS/frontend/pull/209

**Comment by MarioPonte** [comment]
Sim não deixa de ser uma solução, mas a biblioteca já está importada no projeto pelo o que vi na documentação do **frontend** e está lá no ficheiro **package.json**, assim sendo só é preciso colocar o componente no código.

**Comment by devgl96** [comment]
Entendi @MarioPonte ! Eu fiz usando o componente do **shadcn-ui**, mas por conta que era uma importação a mais, eu pensei na renderização e no tamanho do arquivo, por isso, evitei de usar. 

Mas se for o certo, eu desenvolvo uma nova solução usando o **shadcn-ui**.

**Comment by artur-debv** [comment]
Seria uma implementação bacana, quando eu dei um refresh, não tive certeza que fez o refresh na página, da pra usar o Shadcn pra usar esse tooltip, como vi eles já estão usando ele

**Comment by artur-debv** [comment]
> Entendido@MarioPonte! Eu fiz usando o componente do **shadcn-ui** , mas por conta que era uma importação a mais, eu pensei na renderização e no tamanho do arquivo, por isso, evitei de usar.
> 
> Mas se for certo, desenvolvo uma nova solução usando o **shadcn-ui** .

Eu vi o evento que é adicionado, eu curti o evento quando clica no botão de refresh , aquele opacity ajuda demais

**Comment by rhuam** [comment]
Precisamos de 2 reviews de código aqui @SOS-RS/backenders
