### ISSUE TITLE
[BUG] Logo da bóia pós-escrita SOS RS aparece como 🛟 no Desktop

### ISSUE THREAD

**Issue by HbLuca** [SOS-RS/frontend#211]
# Descrição
A bóia circular salva vidas, que na versão mobile aparece de acordo, conforme evidência, no Desktop aparece como um 🛟.

# Problema encontrado
🛟 no "sobre nós" e "política de privacidade" após escrita SOS RS

# Prioridade
- Média

# Solução proposta
Verificar o logo para adapta-lo ao Desktop

# Ambiente
Desktop - Windows 10 (Google Chrome) e Xiaomi Redmi Note 9S

# Evidência
![desk x mob](https://github.com/SOS-RS/frontend/assets/108205892/ec4aee54-af9e-492d-a945-dd1f15243a8c)

**Comment by HbLuca** [comment]
Foram testados no Opera GX, Edge e seguem o mesmo comportamento. 
Firefox está de acordo.

**Comment by andradeviniicius** [comment]
Foi criado PR #219 para tratativa deste problema, aparentemente o unicode da boia 1F6DF nao é suportado pelo chrome e browsers q utilizam a mesma engine

**Comment by artur-debv** [comment]
Eu Testei no Chrome, agora está ok, pelo menos testei em outros navegadores funcionou

**Comment by HbLuca** [comment]
@artur-debv 
Aqui segue da mesma forma...
Realizei o teste no Google Chrome, Ópera GX e Edge.
https://www.loom.com/share/294a3d24897349beb48791cf52aaa424?sid=e128f853-113f-4dc9-9782-516d75012b08

**Comment by rhuam** [comment]
Satisfaz as necessidades de produto.

**Comment by HbLuca** [comment]
Não está de acordo para seguir para merge em produção.
Motivo:
https://dev.sos-rs.com/ está contemplando apenas no sobre nós, falta na parte de política de privacidade, o problema reportado foi em ambos e não apenas em 1.

Vide Loom:
https://www.loom.com/share/2b5cdc8fc88843048975c15ce28595f2?sid=8071a4f4-ceb5-4399-a3b0-ee427395611d

**Comment by andradeviniicius** [comment]
Feito PR #304 dessa vez foi substituído todas as ocorrências de  🛟 pelo lucide-icons

**Comment by larissapissurno** [comment]
PR #304 aprovado e mergeado

**Comment by HbLuca** [comment]
@larissapissurno testado em producao e ja esta contemplado por la, vou encerra-lo.
Vide Loom:
https://www.loom.com/share/1555c63f83a245e4894216fba96f3b66?sid=67318732-48cc-4e4c-9f98-bf6486c266e1
