### ISSUE TITLE
[BUG] Acúmulo de "sujidade" para o BD

### ISSUE THREAD

**Issue by HbLuca** [SOS-RS/frontend#213]
# Descrição
Abrigos com [apagar] após o nome

# Problema encontrado
Caso aumente o nro, pode ser um problema significativo.

# Prioridade
- Baixa, inicialmente. Podendo ir para Media caso acumule mais.

# Solução proposta
Apagar os abrigos, talvez com a mesma base do [178](https://github.com/SOS-RS/frontend/issues/178)?

# Ambiente
Desktop Google Chrome - Windows 10

# Evidência
![image](https://github.com/SOS-RS/frontend/assets/108205892/fea43082-7427-4b56-bfcc-6f6986a33257)

**Comment by JuanGustah** [comment]
@HbLuca Como não há nenhuma forma de alterar o nome do abrigo diretamente da aplicação, alguém com acesso ao banco de dados deve ter alterado diretamente. 
A forma de tratar essa issue e a https://github.com/SOS-RS/frontend/issues/178 seriam a mesma de acordo com a implementação da https://github.com/SOS-RS/frontend/issues/178 de fato, apenas assinalando o campo no banco de dados com um script filtrado por [desativado]  e [apagar] (posso providenciar um), e esses registros não seriam mais exibidos na filtragem.
Mas talvez essas observações nos nomes sejam um indício de que os abrigos entram em contato com os administradores para "remover" eles do banco de dados. Por isso seria interessante uma opção para isso também, como proposto na https://github.com/SOS-RS/frontend/issues/178.

**Comment by HbLuca** [comment]
@JuanGustah entendi.

Bem, se puder providenciar um delete from com where... (Se não estou caducando).

Pode ser, faz mais sentido, ai eles vão e atualizam com esses dizeres "apagar, deletar, desativar"

**Comment by rhuam** [comment]
Duplicada de #269
