### ISSUE TITLE
[BUG] Altura de Navbar divergente entre páginas

### ISSUE THREAD

**Issue by HbLuca** [SOS-RS/frontend#221]
# Descrição
Estava realizando o acesso na versão desktop e ao ir clicando, reparei que a altura estava diferente uma da outra, referente ao Navbar.

# Problema encontrado
Divergência entre Navbar da Home Page, Sobre nós, Apoiadores do projeto e Política de privacidade. Na home está com o 309 x 56, no restante está com o 309 x 48.

# Prioridade
- Baixa

# Solução proposta
Ajustar todos para 309 x 48 ou 309 x 56.

# Ambiente
Desktop Google Chrome - Windows 10

# Evidência
![image](https://github.com/SOS-RS/frontend/assets/108205892/62e05227-e592-48dc-aaea-e966255e2264)

**Comment by HbLuca** [comment]
Correlacionados:
https://github.com/SOS-RS/frontend/pull/63
https://github.com/SOS-RS/frontend/issues/131
https://github.com/SOS-RS/frontend/pull/133
https://github.com/SOS-RS/frontend/issues/215

**Comment by Minozzzi** [comment]
> Correlacionados: #63 #131 #133 #215

É duplicated essa issue?

**Comment by HbLuca** [comment]
@Minozzzi Não, apenas deixei para uma complementar a outra.
Já que 63 pega a tela no geral, 131 sobre navbar ser fixado ao seguir a page, 133 é a realização da fixação do navbar e 215 sobre ter o botão voltar ao topo, mas todos com base na utilização/modificação da home page. 

Este em específico sobre o ajuste do Navbar da home + sobre nós e da política de privacidade.

**Comment by Minozzzi** [comment]
Entendi!

Então são problemas relacionados mas que não resolve este!

Se ninguém se pronunciar, amanhã eu vejo para fazer esse ajuste.

**Comment by HbLuca** [comment]
@Minozzzi correto.
Apenas estou deixando-os entrelaçados para que caso alguém veja, consiga compreender que pode subir tudo junto, para não ter aquele baita trabalhão de sobe uma melhoria ou bug, ai do nada ele volta... E assim vai.

Obs: Os que adiciono de correlação são tanto issues, quando a parte de PR, para compreender o caminho feito. Como é o exemplo da Issue 131 com a PR 133.

De acordo.

**Comment by kevinDsousa** [comment]
Alguem vendo? posso dar uma olhada agora

**Comment by kevinDsousa** [comment]
https://github.com/SOS-RS/frontend/pull/239 Observei que a criação do componente é padrão para os tres casos, mas olhando o botão de reload vi que não tinha um tamanho definido podendo gerar o espaço, apos fixar um tamanho no mesmo o comportamento sumiu

https://github.com/SOS-RS/frontend/pull/239

**Comment by HbLuca** [comment]
@kevinDsousa 
Certo, mas esse caso é referente ao navbar ou a barra que está o SOS Rio Grande do Sul em vermelho, que está com tamanhos divergentes, mas entendo, caso o botão de reload não tenha tamanho definido, neste caso... Poderia ver junto do https://github.com/SOS-RS/frontend/issues/215, caso dê, claro.

**Comment by kevinDsousa** [comment]
@HbLuca Caso é sobre altura do Navbar, altura da "barra que está o SOS Rio Grande do Sul em vermelho" menu fica desalinhado por causa do tamanho do botão do reload

**Antes:**
![image](https://github.com/SOS-RS/frontend/assets/55944691/0305d120-d8b9-4a57-ad03-5aed2dcf0cc7)

**Depois**
![image](https://github.com/SOS-RS/frontend/assets/55944691/94822e00-51be-47b2-944e-68905a687a34)

![image](https://github.com/SOS-RS/frontend/assets/55944691/4fe11afc-21cb-4160-a095-d989f11e2dc2)

![image](https://github.com/SOS-RS/frontend/assets/55944691/756048f7-8ce1-4313-8d62-a492dae7c59f)

**Comment by HbLuca** [comment]
@kevinDsousa que coisa... o.O
Teria de ver então sobre ajustar o botão reload para readequar a barra.

**Comment by kevinDsousa** [comment]
@HbLuca Sim verifiquei os tamanhos das páginas, foi colocado somente o tamanho no botão para encaixar no layout, PR foi aberto

**Comment by HbLuca** [comment]
@kevinDsousa de acordo, muito obrigado!
