### ISSUE TITLE
[BUG] Impossibilidade de fechar o modal de filtrar resultados

### ISSUE THREAD

**Issue by pedroseibel** [SOS-RS/frontend#241]
# Descrição
Impossibilidade de fechar o modal de filtrar resultados, pois fica escondido em baixo da barra de navegação.

# Problema encontrado
Embora exista o botão para fechar o modal de filtrar resultados, ele acaba ficando escondido em baixo da barra de navegação, deixando o usuário preso nessa tela até que a página seja recarregada.

# Solução proposta
O botão para fechar o modal precisa ser reposicionado dentro dos limites visíveis do viewport, de modo que fique acessível ao usuário quando o modal estiver aberto.

# Ambiente
Dispositivo: iPhone 11 
Sistema Operacional: iOS 17.4.1
Navegador: Safari

Dispositivo: Moto E7
Sistema Operacional: Android 10
Navegador: Google Chrome

# Evidência
![Screenshot](https://github.com/SOS-RS/frontend/assets/64672223/6f1bd463-c6f5-41f0-8c74-11758a6cc3b3)

**Comment by kaellandrade** [comment]
Alguém conseguiu reproduzir o bug local?

Apesar de em produção está com esse bug, rodei local e está normal.

Prod:
![image](https://github.com/SOS-RS/frontend/assets/51521476/13f8b3a9-b3c4-4974-9530-611f6e46712c)

Local:
![image](https://github.com/SOS-RS/frontend/assets/51521476/68f00d96-b365-4e22-9661-b2add79f0953)

**Comment by Gacktto** [comment]
![image](https://github.com/SOS-RS/frontend/assets/135454614/9e8415b4-0d41-4232-9d70-b4a08a098ed0)
09:01 18-06

**Comment by SMCodesP** [comment]
Esse problema já foi resolvido, ao menos na branch develop já foi resolvido, confira https://dev.sos-rs.com no instante não foi para produção porém já é um problema resolvido no commit e17170fb3ef27070e913d617b10d3772169420d9. Sugiro que esta issue seja fechada.
