### ISSUE TITLE
Erro de fluxo de merges resultou em bug em produção

### ISSUE THREAD

**Issue by JoaoKremerDev** [SOS-RS/frontend#25]
Como resolver: verificar se a branch master possui novas funcionalidades em relação a branch develop.
Caso não tenha, usar os dados da branch develop como o que deve estar em produção...

Recomendação: padronizar as branchs no seguinte fluxo:
- Produção
- Homologação (fase de testes)
- Desenvolvimento.

A galera que for contribuir só vai ter acesso a branch de desenvolvimento. O código irá subir para a homologação e deve ser testado pelos administradores do projeto e só após testes com 100% de certeza da funcionalidade sem nenhum problema deve de fato subir para a produção.

Lembrem-se de que pessoas estão confiando em vossas informações. Erros devem ser mitigados.

**Comment by fagundesjg** [comment]
Estamos corrigindo este problema, obrigado pelo feedback
