### ISSUE TITLE
Evitar duplicatas no cadastro de novos itens (usando autocomplete na busca)

### ISSUE THREAD

**Issue by giggio** [SOS-RS/frontend#254]
# TL;DR

Mudança no cadastro de novos itens para evitar duplicatas, otimizando a quantificação das demandas. O botão de cadastro de novos itens deixa de existir, a busca vira o meio para cadastrar itens que ainda não existem.

# Problema

<aside>
🗣️ **User story:** Eu sou um doador (CD ou pessoa física). Eu estou tentando entender a necessidade de itens de um abrigo. Mas existem muitos itens similares cadastrados como “água” e “água 1L” porque as pessoas não têm consciência do que já existe o que faz com que eu não consiga entender a demanda de forma clara e objetiva.

</aside>

Precisamos garantir que o registro seja eficiente para o usuário, entregando a informação centralizada. Por isso, é importante que o usuário possa ver quais itens já foram cadastrados e evite cadastrar itens muito similares.

# Design

https://www.figma.com/design/uy6ukD6inEdpvaKVhIyobX/SOS-RS?node-id=1002%3A1052&t=gMoiIFBjpx9R1EX3-1

# Critérios para aceitação

1. O botão de “cadastrar novo item” deixa de existir;
2. O campo de busca habilita a adição de novos itens quando o item digitado não existe. A partir do autocomplete o usuário consegue entender a similaridade entre o item que está buscando e o que deseja adicionar;
3. O campo de busca mostra os itens que já foram cadastrados anteriormente a partir de um autocomplete;
4. Se o item desejado estiver na lista de sugestões, o usuário pode selecioná-lo para evitar criar um novo registro duplicado;
5. Se o item ainda não existe é possível criar um novo item;
6. Existe uma label explicando que o cadastro de novos itens é feito a partir da busca;
7. O sistema deve ser capaz de identificar e diferenciar itens com nomes semelhantes, mas detalhes diferentes.

# Critério de sucesso

Centralização dos itens em uma lista coesa no banco de dados a partir da qual o usuário pode identificar as necessidades e a plataforma pode quantificar as demandas.

**Comment by larissapissurno** [comment]
opa, posso pegar essa @giggio?

**Comment by giggio** [comment]
@larissapissurno Pode, sim! Se precisar de apoio fala com a galera no Discord. Esse item tem prioridade alta, então tem dar uma corrida! Bora!

**Comment by larissapissurno** [comment]
on it! tranquilo, to acompanhando o discord lá, qualquer coisa dou um grito o/

**Comment by larissapissurno** [comment]
pronto pra code review, @giggio, poderia mover pra coluna de revisão? thx!

**Comment by larissapissurno** [comment]
@giggio qq, temos algum SLA por prioridade de tasks? seria legal uma definição nesse sentido, o que acha?

**Comment by giggio** [comment]
Movido!
Pois é, a ideia é que os itens de prioridade alta levem até dois dias, eu mandei um PR no repo de backend pra propor isso.

**Comment by TucanoWeb** [comment]
Opa, bom dia. Veja se a solução abaixo atende:

https://github.com/SOS-RS/frontend/pull/229

- Usuário inicia o cadastro do item e recebe uma lista de itens com caracteres inclusos no input;
- Sistema retorna se o item já é registrado para o próprio abrigo, caso positivo, permite a edição na própria página, de forma muito prática;
- Após o cadastro ou edição, usuário recebe notificação que a ação foi executada com sucesso e retorna para tela de detalhes do abrigo.


![Video_1715941726](https://github.com/SOS-RS/frontend/assets/104173294/4814c2a9-8225-4a59-a511-f9259f1fd377)

**Comment by giggio** [comment]
@TucanoWeb pelo visto temos implementações para resolver problemas parecidos. Criei um tópico no Discord pra discutir como atuar: https://discord.com/channels/1237553809371299950/1242105427697729586

**Comment by rhuam** [comment]
O PR #275  Satisfaz as necessidades de produto para essa issue.

**Comment by larissapissurno** [comment]
@SOS-RS/qas poderiam confirmar se essa issue foi testada em QA?

**Comment by HbLuca** [comment]
@larissapissurno testando aqui...

**Comment by larissapissurno** [comment]
@HbLuca os itens estavam sendo movidos automaticamente pra done quando o PR mergeava, vou mover todos que estao em done e sem comment de QA pra coluna "Disponível pra QA", tudo bem?

**Comment by HbLuca** [comment]
@larissapissurno 
Realizado, seguindo o passo a passo e vendo o design...
Fica aberto alguns questionamentos.

1 - Ficará a cargo/boa fé do povo? Já que vi que o cenário 1 foi o único que atendeu no ambiente de Q.A, Prod e Dev, cenário 2 e 3 não foram contemplados.

2 - Não existe aviso sobre duplicação de item, apenas o que ocorre é caso adicione o item com modificação de prioridade e quantidade, ele deixa o valor atual e nem a mensagem de erro sobre item não encontrado.

3 - Ao pesquisar, por exemplo bombona de água que está em Eletrodomésticos e Eletrônicos e adiciona-lo em outro local como Equipamentos de Emergência, ele está sendo aceito. Local realizado: Igreja Lugar de adoração.

Vide Loom:
https://www.loom.com/share/8fac76d373db4110b21206aeb38eda59?sid=c323be42-f251-4158-a78b-020c2e7c97eb

**Comment by HbLuca** [comment]
@larissapissurno sem problemas, pode mover... Apenas uma dúvida, todos estão mergeados para o ambiente de QA?
Se quiser, testo nos 3 sem problemas para fazer comparativo.

**Comment by larissapissurno** [comment]
oi @HbLuca, obrigada pelo rápido retorno 🚀  

> [@larissapissurno](https://github.com/larissapissurno) Realizado, seguindo o passo a passo e vendo o design... Fica aberto alguns questionamentos.
> 
> 1 - Ficará a cargo/boa fé do povo? Já que vi que o cenário 1 foi o único que atendeu no ambiente de Q.A, Prod e Dev, cenário 2 e 3 não foram contemplados.

não sei se entendi corretamente, mas se estiver se referindo ao fato de continuar deixando qualquer pessoa adicionar o item, eu concordo com vc em partes, por um lado eu penso que deixar qualquer pessoa cadastrar qualquer coisa é um pouco arriscado, mas por outro, se deixarmos essa responsabilidade para o lado do sistema, isso pode causar um gargalo no lado do sistema no sentido de termos que gerenciar isso via bando de dados e talvez criar uma interface pro usuário solicitar uma adição de item talvez? No mais acho bem válido seu ponto, pra mim faz sentido trazermos isso pro time de produto pensar junto com a gente, o que acha? 

 
> 2 - Não existe aviso sobre duplicação de item, apenas o que ocorre é caso adicione o item com modificação de prioridade e quantidade (Não sei se isso seria algo agravante, lembrando que isso é continuidade do 1), ele deixa o valor atual e nem a mensagem de erro sobre item não encontrado é apresentado.

ótimo ponto, temos uma explicação pra isso. Se observar o PR, vai ver que temos um possível PR duplicado, acontece que o PR duplicado implementa apenas a validação no cadastro, enquanto o meu PR implementa o autocomplete, no tópico que estou linkando abaixo concordamos em seguir com os dois PRs, porém o outro não foi mergeado ainda, acho que podemos linkar ele nessa issue tbm e  colocar ela on hold até termos o outro PR enviado para QA, o que acha? 

https://discord.com/channels/1237553809371299950/1242105427697729586

PR de validação no cadastro: https://github.com/SOS-RS/frontend/pull/229

> 3 - Ao pesquisar, por exemplo bombona de água que está em Eletrodomésticos e Eletrônicos e adiciona-lo em outro local como Equipamentos de Emergência, ele está sendo aceito. Local realizado: Igreja Lugar de adoração.

como mencionado acima, o PR https://github.com/SOS-RS/frontend/pull/229 deve corrigir este problema

**Comment by HbLuca** [comment]
@larissapissurno 

1 - Sim, referente as pessoas mesmo. Faz sentido o parcial, podemos ver sim, mas acredito que seja a mesma tratativa/resposta referente a cadastro de locais, que seguirá aberto. 
Referente aos cenários, são sobre o que está no figma... Que existem 3 cenários e apenas 1 foi contemplado.

2/3 - Ótimo, o de autocomplete está de acordo, ao digitar algumas letras ele já faz o serviço. Referente ao item, é um pouco mais delicado, já que ele pode ser algo de necessidade urgente e ai alguém colocar como apenas necessário ou até modificar quantidade, se tiver controle de log, BD "vai cantar"... O 229 é interessante pelo aviso, mas deve ver de bloquear e não deixar ir até o pop-up.

**Comment by TucanoWeb** [comment]
@larissapissurno e @HbLuca, boa noite. Como estão?

Recebi a notificação de referência à PR. A que inclui a validação e a limitação na página de cadastro é a https://github.com/SOS-RS/frontend/pull/296

Importante destacar que a ideia de agregar as soluções já havia sido proposta, brilhantemente, pela @larissapissurno.

**Comment by larissapissurno** [comment]
> Referente ao item, é um pouco mais delicado, já que ele pode ser algo de necessidade urgente e ai alguém colocar como apenas necessário ou até modificar quantidade, se tiver controle de log, BD "vai cantar"... O 229 é interessante pelo aviso, mas deve ver de bloquear e não deixar ir até o pop-up.

@HbLuca entendo, sera entao que poderiamos deixar mais claro que ele está editando um item existente? lembrando que hoje já é possivel alterar essas informações ali na lista de items para o abrigo

**Comment by HbLuca** [comment]
Boa noite @TucanoWeb estou bem e tu?

Hmmm... Com a 296 (a mergear) e 275 (mergeado) já teriamos o autocomplete e também a "trava" referente a duplicação.

@larissapissurno no 296 passado pelo @TucanoWeb acredito que já ocorra isso de deixar claro sobre item existente (ao menos vendo os vídeos compreendi isso).

Parabéns aos 2.

**Comment by larissapissurno** [comment]
mergeei o PR do @TucanoWeb, vou add no PR de release pra staging

**Comment by larissapissurno** [comment]
temos esse bug que pode estar relacionado ao autocomplete: https://github.com/SOS-RS/frontend/issues/298

**Comment by HbLuca** [comment]
@larissapissurno, sim... está mesmo!

**Comment by HbLuca** [comment]
@larissapissurno só temos um porém...
https://github.com/SOS-RS/frontend/issues/305
Nesta issue, é relatado que existe duplicidade de itens na parte de busca de itens.
Possívelmente isso que pode acarretar conforme imagem abaixo:
![image](https://github.com/SOS-RS/frontend/assets/108205892/bb90261d-3cdb-4076-b235-b384f2d4844e)
Não me deixa cadastrar água, mas aparecem água, agua, água sanitária 2x...

**Comment by TucanoWeb** [comment]
@HbLuca, bom dia. Essa redundância ocorre devido aos registros retornados do banco de dados. 

Essa normalização vai ocorrer pelo DB, backend ou esse controle vai acontecer somente no front? Se não for via front, acredito que as issues relacionadas podem ser fechadas e uma nova aberta no back.

Via DB, na minha opinião, é:
- Localizar os registros duplicados, considerando os items registrados, não as necessidades registradas. Acredito que a normalização do retorno da consulta utilizando lower e translate resolva a questão;
- Alterar, em massa, o ID do supply que está sendo referenciado na tabela de supplies (itens necessários), considerando o registro que será persistido ;
- Deletar os registros dos supplies registrados em duplicidade.

**Comment by HbLuca** [comment]
@TucanoWeb não poderia modificar esta issue para FULL?
E com isso seguir por ela com a parte back e no "development" adicionar a pr de back?

**Comment by TucanoWeb** [comment]
> @TucanoWeb não poderia modificar esta issue para FULL? E com isso seguir por ela com a parte back e no "development" adicionar a pr de back? Caso sim, realizaria o teste por aqui mesmo e ai finalizaria com as 3 pr`s... 2 de front e 1 back.

Boa noite @HbLuca. 

Acredito que somente no back já seja o suficiente. Se vocês concordarem, pode abrir a Issue no back e me dar um toque que eu faço esse ajuste.

**Comment by larissapissurno** [comment]
@HbLuca os ajustes pendentes já estão todos em staging, poderia verificar novamente? 🙏

**Comment by HbLuca** [comment]
@larissapissurno vou verificar e ja criei um em back, @TucanoWeb caso queira ver...

**Comment by HbLuca** [comment]
@larissapissurno feito.
Realizado teste do autocomplete, realizado teste de identificacao de duplicidade e criacao de novo item, mostrando que existem itens com proximidade de nome Suco de laranja testado na Casa Da Criança Nossa Senhora Auxiliadora.
Vide loom: https://www.loom.com/share/1be198fd0cb74d9a99e49f1754c8987f?sid=9c987bad-0d0e-4db9-baef-0b0308fb9149
