### ISSUE TITLE
[BUG] Pagina sem monitoramento de scroll

### ISSUE THREAD

**Issue by williandeitosi** [SOS-RS/frontend#265]
# Descrição
A página não está retornando o valor correto do scroll mesmo quando o usuário rola verticalmente..

# Problema encontrado
Quando a página é rolada verticalmente, o valor de window.scrollY não está sendo atualizado corretamente, retornando sempre 0 independentemente da posição de rolagem atual. Isso impede a funcionalidade que depende do valor do scroll, como a exibição de botao voltao ao topo que é a funcionalidade que eu estou tentando desenvolver.

# Prioridade
Registre apenas a prioridade ou seriedade do defeito. Um guia:

- Média

# Solução proposta
o valor de window.scrollY refletisse corretamente a posição de rolagem vertical da página.

# Ambiente
Testado no navegador Google Chrome em um computador Windows 11.

# Evidência
![Captura de tela 2024-05-19 085443](https://github.com/SOS-RS/frontend/assets/104787632/10d3c826-b18f-4042-a906-16dfef6eca49)

**Comment by allangalera** [comment]
Pelo visto isso é causado pq o `#root` tem um `overflow: hidden`. Testei algumas páginas e não parece ter efeito nenhum quando eu removo 🤔 

![image](https://github.com/SOS-RS/frontend/assets/12666793/f2a94fab-5346-4f65-8920-39f71546fd08)


Alguem sabe se tem algum motivo pra esse `overflow: hidden` ter sido adicionado ou é seguro remover?

>  Isso impede a funcionalidade que depende do valor do scroll, como a exibição de botao voltao ao topo que é a funcionalidade que eu estou tentando desenvolver.

Concordo q seria mais fácil utilizar o métodos da `window` pra criar efeitos de scroll, porém isso não impede de criar funcionalidades de scroll. Sabendo que é a div com id `#root` é possível adicionar eventos de scroll sem problemas
