### ISSUE TITLE
[BUG] Duplicação do Título "Apoiadores" em Produção

### ISSUE THREAD

**Issue by rhuam** [SOS-RS/frontend#268]
Precisamos corrigir a duplicação do título "Apoiadores" que aparece duas vezes apenas no ambiente de produção, garantindo que a interface seja exibida corretamente.

**Problema**

**User story:** Eu sou um usuário do sistema em produção. Eu estou tentando visualizar a página de apoiadores. Mas o título "Apoiadores" aparece duas vezes, o que causa confusão e afeta a experiência do usuário.

É essencial que a interface de produção exiba o título "Apoiadores" apenas uma vez, garantindo uma visualização clara e profissional da página.

Critérios para aceitação
- O título "Apoiadores" deve aparecer apenas uma vez na página de apoiadores no ambiente de produção.
- Verificar e corrigir quaisquer duplicações de componentes no código que possam estar causando esse problema.
- Garantir que a interface esteja consistente entre os ambientes de desenvolvimento, staging e produção.

**Comment by elfiservice** [comment]
iniciando com esse Bug

**Comment by elfiservice** [comment]
seria bom eu poder assinar ela para Mim

**Comment by elfiservice** [comment]
hi guys 
Na branch `develop` isto esta correto. Devido o problema ocorreu nesse merge de Staging: 
- https://github.com/SOS-RS/frontend/commit/c7f37dd298a0fab8392885199ed5f91062b7bca4#diff-6b8db48d554e056dea1bf640b1a762250ab726da6bf70ba27a84cd3136d8cb8b

provavel quando foi resolver os conflitos acabou ficando os components duplicados.

Entao, nao consigo acessar o branch `master` para abrir um fix direto pra lá. O proximo merge da develop pra master deverá resolver.

Mas se souberem como me dar acesso ao branch `master` fazemos logo a correção.
grato

**Comment by sr2ds** [comment]
@elfiservice 
Acredito que se está correto na `develop` e errado na `staging`(caso ela já esta atualizada), o ideial é puxar a `staging` para `develop` fazendo a corração necessária e aguardar a próxima release. Fazer a correção na `master` pulando as etapas pode complicar o processo a longo prazer, caso comece a acontecer isso, ainda mais que não é um bug crítico.

**Comment by elfiservice** [comment]
@sr2ds 
Boa, entendi.
Conferi aqui, na `staging` esta corrigido tb
Apenas na `master` esta apresentando o codigo duplicado.

teria como atualizar a `develop` com a `master` ?

**Comment by sr2ds** [comment]
> @sr2ds Boa, entendi. Conferi aqui, na `staging` esta corrigido tb Apenas na `master` esta apresentando o codigo duplicado.
> 
> teria como atualizar a `develop` com a `master` ?

Boa!  Em teoria, se a `develop` está correta, e já foi para `staging`, o próximo passo é aguardar a entrada para `master`.

Podemos chamar essa entrada para master de `release`, geralmente acontece depois da galera de qualidade confirmar que está tudo bem em `staging`.

Apesar que honestamente não tenho certeza se estamos seguindo esse fluxo completo aqui.

**Comment by larissapissurno** [comment]
movendo para "Disponível para QA", pois foi movida automaticamente para "Done" ao mergear o PR

**Comment by HbLuca** [comment]
@larissapissurno pode seguir fechado, este.
Já mergiaram em todos os ambientes, de acordo.

Segue Loom:
https://www.loom.com/share/633e82ccf9764196b39f9a1752b79969?sid=f7fbeb57-3aa7-48d3-b3fe-15246eaf029f
