### ISSUE TITLE
Padronizar Termos: Alterar "necessita urgentemente" para "precisa com urgência"

### ISSUE THREAD

**Issue by rhuam** [SOS-RS/frontend#284]
Precisamos garantir a padronização dos termos utilizados no sistema, substituindo "necessita urgentemente" por "precisa com urgência" para manter a consistência e clareza.

**Problema**

**User story:** Eu sou um usuário do sistema. Eu estou tentando entender as necessidades de itens no sistema. Mas a inconsistência nos termos usados, como "necessita urgentemente" e "precisa com urgência", causa confusão e dificulta a compreensão das prioridades.

É essencial que o sistema utilize termos padronizados para garantir que todos os usuários possam compreender facilmente as necessidades e prioridades dos itens.

Critérios para aceitação
- Todos os textos no sistema que utilizam "necessita urgentemente" devem ser alterados para "precisa com urgência".
- A alteração deve ser refletida em todas as interfaces de usuário, incluindo campos, botões, rótulos e mensagens.
- A mudança deve ser implementada tanto no frontend quanto no backend, se necessário.
- Realizar testes para garantir que todas as instâncias do termo foram atualizadas corretamente.

**Comment by rayanerocha07** [comment]
Vou instalar o projeto e tentar fazer essa.

**Comment by rayanerocha07** [comment]
https://github.com/SOS-RS/frontend/pull/288 @rhuam

**Comment by rhuam** [comment]
@SOS-RS/frontenders alguém pode revisar?

**Comment by larissapissurno** [comment]
movendo para "Disponível para QA", pois foi movida automaticamente para "Done" ao mergear o PR

**Comment by HbLuca** [comment]
@larissapissurno de acordo.
Filtros > Status do item por abrigo;
No informativo do local (Abrigo ou CD...);
Selecionando o local no Itens do abrigo;
Clicando em editar itens;
Selecionando um item e verificando no pop-up para a escolha de prioridade de item.
Dev, QA e Prod.

Vide Loom:
https://www.loom.com/share/218d95c75bb24d1fbc47abe9eb3d9aa4?sid=e5fb60d0-66fe-4e13-bdda-7d1976bf221a
