### ISSUE TITLE
[BUG] Inserir nomes de itens com apenas números.

### ISSUE THREAD

**Issue by amaurybritoo** [SOS-RS/frontend#285]
# Descrição
- Ao tentar adicionar um novo item, o site permite que o nome do item contenha apenas números.

# Problema encontrado
- O site permite que o nome do item contenha apenas números.

# Prioridade
- Baixa

# Solução proposta
- Verificar se o input contém apenas números, o site deve exibir uma mensagem de erro indicando que o nome do item não pode conter apenas números e deve incluir pelo menos um caractere alfabético.

# Ambiente
- SO: Win11 pro.
- Navegador: Google Chrome 124.0.6367.208

# Evidência

https://github.com/SOS-RS/frontend/assets/117760670/0a9e7458-88d8-4c8c-b9ff-1e7555d3d6fa

![evidencia02](https://github.com/SOS-RS/frontend/assets/117760670/41896912-2411-4bb7-853f-0d840447653c)

**Comment by fagundesjg** [comment]
Acabei de testar esse bug no ambiente de [dev]( https://dev.sos-rs.com) e conforme imagem abaixo, cadastrei o suprimento teste 123 no neste abrigo [aqui](https://dev.sos-rs.com/abrigo/19c7dc7c-74aa-4a9a-a4c7-2ad228e71cda/items).

![Captura de Tela 2024-05-22 às 10 49 22](https://github.com/SOS-RS/frontend/assets/29789354/e685458b-b3b0-4906-8985-9526d020e47b)

Pelo vídeo percebo que estava rodando uma branch desatualizada ou pior, testando em produção.

**Comment by TucanoWeb** [comment]
A resolução dessa issue está inclusa na PR https://github.com/SOS-RS/frontend/pull/296

**Comment by larissapissurno** [comment]
@rhuam PR pra mandar o #296 ainda está aguardando revisão, preciso de ao menos 1 approval pra mergear em staging: https://github.com/SOS-RS/frontend/pull/311
