### ISSUE TITLE
[BUG] Filtros não persistem ao retornar de um abrigo específico.

### ISSUE THREAD

**Issue by ThiagoBritoo** [SOS-RS/frontend#291]
# Descrição
Os filtros aplicados na lista de abrigos são perdidos ao navegar para a página de detalhes de um abrigo e retornar à lista principal.

# Problema encontrado
Os filtros aplicados na lista de abrigos não persistem ao retornar à página anterior por meio da navegação do site.

# Prioridade
- Média: defeito não tão sério, mas que dificulta o uso da aplicação de modo geral.

# Solução proposta
Os filtros aplicados devem persistir após a navegação para a página de detalhes de um abrigo e o retorno à lista principal.

# Ambiente
SO: Windows 11
Navegador: Google Chrome 

# Evidência
https://www.loom.com/share/e4a35e4e50d44c90b0adacf1f4ab4f12?sid=e9180b27-197d-4823-80bc-9f5ec8cb0bab

**Comment by Johnviti** [comment]
Posso realizar esse item?

**Comment by Johnviti** [comment]
Vou está dando início agora

**Comment by Johnviti** [comment]
Criei uma lógica para persistir os filtros usando localStorage

**Comment by Johnviti** [comment]
Realizando testes para subir o PR

**Comment by Johnviti** [comment]
Fix: persist filters on return #309

**Comment by HbLuca** [comment]
Não é possível realizar os testes, ambiente de Q.A indisponivel, de DEV indisponivel.
