### ISSUE TITLE
[BUG] Seleção de itens na tela de edição

### ISSUE THREAD

**Issue by rhuam** [SOS-RS/frontend#298]
Segue video do BUG.
Itens que não aparecem no filtro, por causa do limite, não podem ser alterados/incluídos.

https://github.com/SOS-RS/frontend/assets/17427907/3560e2c1-a501-470a-961d-1a53597807d2

**Comment by TucanoWeb** [comment]
@rhuam , acredito que a PR resolva essa questão:

https://github.com/SOS-RS/frontend/pull/296

**Comment by rhuam** [comment]
Aguardando revisão de código @SOS-RS/backenders

**Comment by TucanoWeb** [comment]
@larissapissurno, bom dia. Essa issue foi resolvida pela PR https://github.com/SOS-RS/frontend/pull/300

**Comment by larissapissurno** [comment]
opa, perfeito!

**Comment by HbLuca** [comment]
@larissapissurno, de acordo.

Ao realizar a pesquisa em Editar Itens, com o autocomplete e ordenação, esta funcionando conforme PR 300.

Vide Loom:
https://www.loom.com/share/8338fd78fd2145c69736ac5c6fd0205c?sid=1e58af5e-e478-4ca9-b155-c6f9cbf6b0a1

Obs: Casa Da Criança Nossa Senhora Auxiliadora foi realizado o teste com pa... e funcionou.
