### ISSUE TITLE
Action aws-actions/configure-aws-credentials@v1 gerando warnings durante deploy

### ISSUE THREAD

**Issue by lucianomlima** [SOS-RS/frontend#30]
<img width="1296" alt="Screen Shot 2024-05-09 at 18 03 14" src="https://github.com/SOS-RS/frontend/assets/1580205/a65838fb-f97f-4d67-924c-0f805927adfc">

Provavelmente atualizar a action resolva isso e ainda deixa de usar versões do node obsoletas.

**Comment by filipefraga** [comment]
@lucianomlima , consegue entrar no Discord pra ficar mais por dentro do projeto? https://discord.gg/UXt5rrgn

**Comment by lucianomlima** [comment]
Done! ✅
