### ISSUE TITLE
[BUG] No filtro dentro do item, há duplicação de itens na lista e informações pessoais de usuários

### ISSUE THREAD

**Issue by AmandaLuizaFreitas** [SOS-RS/frontend#305]
No filtro aplicado dentro de um item específico, estou encontrando dois problemas:
- A lista exibida está com itens duplicados.
- Informações pessoais de usuários estão sendo exibidas  

https://github.com/SOS-RS/frontend/assets/110351770/bb07df26-8f3a-44de-b0d1-1c2e0a6cdce2

**Comment by Johnviti** [comment]
Boa noite! vou realizar a correção

**Comment by AmandaLuizaFreitas** [comment]
Johnviti obrigada

**Comment by Johnviti** [comment]
![image](https://github.com/SOS-RS/frontend/assets/84483840/6ada6761-bde7-49c7-9e57-e71a3ab402e1)
Vou tentar baixar e rodar o back para verificar, mas creio que deveria ter algum tratamento para a inserção dos nomes dos itens ou algum tipo de abordagem que previna a criação de duplicatas, estou verificando no momento como é realizado o fluxo de busca e inserção desses dados

**Comment by Johnviti** [comment]
![image](https://github.com/SOS-RS/frontend/assets/84483840/e798b944-1caf-4a22-8384-ccf9be7dd525)

Realizei alguns ajuste para atenuar o problema das duplicatas, porém devera ser aberta uma task no back, para validação ao inserir um novo item no banco de dados, o backend deve verificar se um item similar já existe.

**Comment by Johnviti** [comment]
@AmandaLuizaFreitas Podemos fechar esse item, fizeram um tratamento no back, devido a isso não temos mais duplicatas em produção
