### ISSUE TITLE
Adicionar link para o site

### ISSUE THREAD

**Issue by salescamila** [SOS-RS/frontend#31]
Sugiro adicionar na descrição do projeto e na coluna About o link para o site 

https://sos-rs.com/

Exemplo: 
![image](https://github.com/SOS-RS/frontend/assets/16194059/10b5c743-1f15-4298-a1a6-e04a69706d66)

**Comment by MatheusDubin** [comment]
@fagundesjg Podes adicionar por favor?

**Comment by salescamila** [comment]
Link adicionado no about do projeto
