### ISSUE TITLE
Criar tela de "Lista de pedidos"

### ISSUE THREAD

**Issue by rhuam** [SOS-RS/frontend#327]

**Comment by robalerod** [comment]
### Job Story

Quando eu confirmar um atendimento, quero poder acessar os seus detalhes para poder imprimir, confirmar entrega ou cancelar o mesmo, assim poderei fazer a gestão do mesmo.

### Requisitos
- Mostrar duas lista de atendimentos, uma para doações doadas e outro para recebidas.
- Quando o status do atendimento for PENDENTE mostrar:
   - Nome da instituição;
   - Hora da **criação do atendimento**;
   - Lista de produtos;
   - Opção para Imprimir
   - Opção para Confirmar;
   - Cancelar;
- Quando tocar em Imprimir, entrar no fluxo de impressão.
- Quando tocar em cancelar, solicitar confirmação. Ao confirmar, alterar o pedido para o status cancelado.
- Quando tocar em Confirmar, alterar pedido para o status ENTREGUE.
- Quando o status do atendimento for ENTREGUE mostrar:
   - Nome da instituição;
   - Hora da **entrega**;
   - Lista de produtos;
   - Opção para Imprimir
- Quando o status do atendimento for CANCELADO mostrar:
   - Nome da instituição;
   - Hora da **do cancelamento**;
   - Lista de produtos;
   - Opção para Imprimir

Design
https://www.figma.com/design/uy6ukD6inEdpvaKVhIyobX/SOS-RS?node-id=3211-18062&t=Abg177xzghyamODA-4

**Comment by souzadediogo** [comment]
@rhuam pode alocar para mim nesse sprint

**Comment by souzadediogo** [comment]
Buenas, @rhuam e @robalerod !

Queria confirmar 3 dúvidas de dois pontos dessa Issue para iniciar o desenvolvimento:

**Impressão da Doação**: 
 > 1. A funcionalidade de gerar PDF para impressão está fora dessa issue, correto?

**Cancelar Doação**: 
 > 2. No Figma não encontrei o botão de cancelar. Posso alocar ele ao lado direito do botão de confirmação?
 > 3. Quem pode cancelar o pedido? Apenas o usuário que criou, quem criou e quem receberá ou qualquer pessoa?

**Comment by rhuam** [comment]
Impressão da Doação:

> A funcionalidade de gerar PDF para impressão está fora dessa issue, correto?
Não. Ela é um task separada #328 

Cancelar Doação:

> No Figma não encontrei o botão de cancelar. Posso alocar ele ao lado direito do botão de confirmação?
Pode sim, só seguir o mesmo layout.

> Quem pode cancelar o pedido? Apenas o usuário que criou, quem criou e quem receberá ou qualquer pessoa?
Apenas quem criou o pedido.

@robalerod se quiser complementar.

**Comment by robalerod** [comment]
Perfeito @rhuam.

@souzadediogo sobre o botão cancelar, a designer vai fazer hoje a noite. Inclusive tem estes pontos abaixo que ela vai fazer:
- Botão cancelar
- Confirmação para cancelar pedido
- Cenário de atendimento com o status cancelado

**Comment by souzadediogo** [comment]
Perfeito, @robalerod .

O @alansSxsx está ajudando nessa task e levantou um ponto que não ficou claro para nós no Figma. 

Como o usuário chega na tela de listagem de doações?

**Comment by robalerod** [comment]
@souzadediogo @alanSxSx @rhuam 

Em primeiro lugar o nome "Listagem de doação" não o que mesmo nome que Design esta usando. Estamos usando "Histórico de doações".

Dois caminhos levam o usuário para lá:
1- Quando ele cria um atendimento de doação, na tela de sucesso tem um botão "Verificar histórico de doações".
2- No menu precisa ter uma opção "Doações" ou "Histórico" ou "Atendimentos". Vou pedir para a Designer definir.

**Comment by souzadediogo** [comment]
@robalerod perfeito!

-  Vou ajustar os componentes com a nomenclatura em acordo com o design "Histórico de doações";
- Vi que o botão de histórico está lá no carrinho já. @fagundesjg , se quiseres já deixar pronto o navigate(), ficou como '/doacoes/:shelterId';

**Comment by souzadediogo** [comment]
@fagundesjg , quando tiveres o schema do banco e/ou a estrutura que virá da API das doações compartilha conosco, por favor?

Aí já ajusto esses componentes de acordo.

**Comment by alanSxSx** [comment]
Eu não consegui entender direito o botão do menu. Ele vai redirecionar pro histórico de qual shealter ?
