### ISSUE TITLE
Adicionar forma de feedback

### ISSUE THREAD

**Issue by Lacerda53** [SOS-RS/frontend#34]
A ideia seria adicionar forma de feedback onde as pessoas pudessem falar o que ta funcionando bem e o que poderia ser melhorado.

**Comment by Matheusroliv** [comment]
Concordo. Mas seria mais simples apenas criar um formulário no Google Docs igual o formulário de cadastro para novos abrigos

**Comment by renatoastra** [comment]
Acho uma boa ideia, porem creio que tem coisas que poderiam ser priorizadas, como o proprio formulario de cadastro de abrigos

**Comment by AndersonCRocha** [comment]
Com base na ideia inicial e no comentário do @Matheusroliv dá pra pegar o melhor dos dois mundos, criar o formulário no google docs e adicionar o link em algum lugar na tela, não vai comprometer tempo quase algum pra add esse link no front

**Comment by okayosilva** [comment]
O form já foi criado? posso implementar a funcionalidade no footer, acho ser um lugar bacana, ou um botão flutuando no canto da tela.

**Comment by MatheusDubin** [comment]
Está sendo resolvido com o https://github.com/SOS-RS/frontend/pull/84 que vai ser mergado em seguida ;)
