### ISSUE TITLE
Case sensitives para filtros.

### ISSUE THREAD

**Issue by renatoastra** [SOS-RS/frontend#35]
Creio que isso seria de grande ajuda para as pesssoas, principalmente aquelas que estao em dispositivos que tem auto complete.

Exemplos:

![image](https://github.com/SOS-RS/frontend/assets/82223861/d571e81f-1d0d-4df9-8b36-271c20c29b01)

![image](https://github.com/SOS-RS/frontend/assets/82223861/b73285c9-3b89-432f-a65b-9106936f758f)

**Comment by MatheusDubin** [comment]
Boa @renatoastra, (implementamos)[https://github.com/SOS-RS/backend/pull/18] e já está em produção!
