### ISSUE TITLE
Metodologia Ágil 

### ISSUE THREAD

**Issue by Victorcassiano** [SOS-RS/frontend#56]
Acredito que seria bom adicionar o Trello, ou algo do similar, ao projeto para organizar as tasks.
Possa ser que futuramente um DEV crie uma commit já existente.

**Comment by okayosilva** [comment]
O trello ja esta em funcionamento, junto com as demais ferramentas que estão elencadas em links úteis no discord, link do trello: https://trello.com/b/YlbqtbDM/backlog-sos-rs
