### ISSUE TITLE
Poderiam passar link do Discord?

### ISSUE THREAD

**Issue by rodrigodsluz** [SOS-RS/frontend#69]
Gostaria de ajudar vcs, e tbm tenho outros amigos q podem ajudar, mas precisamos alinhar algumas coisas e pegar o contexto, poderiam passar o link?

**Comment by GiovaniBiagi** [comment]
Procurando também! Algum outro canal de comunicação?

**Comment by okayosilva** [comment]
aqui pessoal: https://discord.gg/BfxdJHPs

**Comment by GiovaniBiagi** [comment]
God demais! Valeu @okayosilva!
