### ISSUE TITLE
[SUGESTÃO] Textos  e imagens prontas para facilitar a divulgação

### ISSUE THREAD

**Issue by RafaGiaretta** [SOS-RS/frontend#83]
Adicionar alguns textos , imagens e videos para rede social ja prontos, para facilitar o compartilhamento no [README.md](https://github.com/SOS-RS/frontend/blob/develop/README.md).

**Comment by MatheusDubin** [comment]
Vamos estar mergando o [seu PR](https://github.com/SOS-RS/frontend/pull/85/files) Rafa, obrigado pela contribuição!
