### ISSUE TITLE
Erro na branch Develop ao rodar o projeto

### ISSUE THREAD

**Issue by lucaoskaique** [SOS-RS/frontend#86]
Fui rodar a primeira vez e há um erro ao abrir o projeto usando a branch develop. A master funcionou normalmente.

![image](https://github.com/SOS-RS/frontend/assets/20323741/4f2c7f02-c03b-44fe-bf54-e6f121d50c08)

**Comment by filipepacheco** [comment]
Acho que não tinhamos visto esse erro antes.
Mais alguém com esse problema?
Tá com a develop mais atual?

**Comment by filipepacheco** [comment]
Vou fechar aqui porque você consegue suporte melhor e mais rápido se postar lá no nosso Discord.
Obrigado!
